# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cublasGemm <- function(A, B, C, type, type_flag) {
    invisible(.Call('_gpuRcublas_cublasGemm', PACKAGE = 'gpuRcublas', A, B, C, type, type_flag))
}

cusolverXgetrf <- function(A, PIV, LU, PIV_FLAG, type, type_flag) {
    invisible(.Call('_gpuRcublas_cusolverXgetrf', PACKAGE = 'gpuRcublas', A, PIV, LU, PIV_FLAG, type, type_flag))
}

cusolverGesvd <- function(A, S, U, VT, type, type_flag) {
    invisible(.Call('_gpuRcublas_cusolverGesvd', PACKAGE = 'gpuRcublas', A, S, U, VT, type, type_flag))
}

